---
title: " ><(((> Super Duper Square Roots HW3 <)))>< "
author: "Izzy Gaw"
date: "2020-01-27"
output: html_document
---


<html>
<head>
<style>
body {background-color: powderblue;}
h1   {color: orange; font-family:Verdana;}
p    {color: white; font-family: verdana;}
</style>
</head>
<body>
<p>



Hello! This page is Izzy's Homework 3 for R Bootcamp.

On this page, you will find my code and examples of a custom Square Root Function.
 
To use this function, you input an x, myguess (which both are used to find the square root), the tolerance (which is the amount of deviation allowed from the actual answer), and verbose (which if turned off will not show all the output of the conditionals (default), but if TRUE will show). 
Additionally, this function works by taking the value for myguess and getting closer and closer to the square root value until it is within the error range you set. 
This will get you to the correct square root for your input! Below the function definition, you will find examples of this function in use.


Lastly, because you cannot input negatives into a square root, you will recieve an error message if you try.

Have fun using this square root function! 


```{r}

mysqrt <- function( x=81, tol=.000001, myguess=27, verbose=FALSE){  

	newguess <- myguess 
	
	if (x>0) { 
	
	approxy <- x/newguess 
	newguess <- (newguess+approxy)/2 
	error = newguess - approxy 
	error <- abs(error) 
	error < tol 
	
	if (verbose==T) {print(error < tol)} 
	if (verbose==T) {print(newguess)} 
	if (verbose==T) {print(error)} 

	while ( error > tol ) { 
	  approxy <- x/newguess  
	  newguess <- (newguess+approxy)/2  
	  error = newguess - approxy 
	  error <- abs(error)  
	  if (verbose==T) {print(error < tol)} 
	  if (verbose==T) {print(newguess)} 
	  if (verbose==T) {print(error)} 
	}
	
	return( newguess ) 
	}else print("BAD. DO NOT USE NEGATIVES") 

}


mysqrt(16) 
mysqrt(16, verbose=TRUE) 
mysqrt(-16)
mysqrt(49)
mysqrt(-49)
mysqrt(49, verbose=TRUE)
mysqrt(361)
mysqrt(-361)
mysqrt(361, verbose=TRUE)
mysqrt(10000)
mysqrt(-10000)
mysqrt(10000, verbose=TRUE)
mysqrt(810000)
mysqrt(-810000)
mysqrt(810000, verbose=TRUE)

```